cursor            #d3bcfd
cursor_text_color #39265c

foreground            #e7e0e8
background            #0f0d13
selection_foreground  #342d40
selection_background  #cdc2db
url_color             #cdc2db

#: black 000000 767676
color0  #151218
color8  #36343a

#: red cc0403 f2201f
color1  #12111b
color9  #504d78

#: green 19cb00 23fd00
color2  #cdc2db
color10 #e9def8

#: yellow cecb00 fffd00
color3  #f0b7c5
color11 #ffd9e1

#: blue 0d73cc 1a8fff (Modified to use Primary)
color4  #d3bcfd
color12 #ebddff

#: magenta cb1ed1 fd28ff (Modified to use bright Secondary instead of dark text variant)
color5  #cdc2db
color13 #e9def8

#: cyan 0dcdcd 14ffff (Modified to use Primary for Fastfetch Arch Logo)
color6  #d3bcfd
color14 #ebddff

#: white dddddd ffffff
color7  #cbc4cf
color15 #e7e0e8

mark1_foreground #230f46
mark1_background #ebddff
mark2_foreground #1f182b
mark2_background #e9def8
mark3_foreground #31101b
mark3_background #ffd9e1

active_tab_foreground #39265c
active_tab_background #d3bcfd
inactive_tab_foreground #ebddff
inactive_tab_background #503d74

active_border_color #d3bcfd
inactive_border_color #39265c
# bell_border_color #ff5a00
