cursor            #ffb0d0
cursor_text_color #531d38

foreground            #eedfe2
background            #130c0f
selection_foreground  #412a33
selection_background  #e1bdc9
url_color             #e1bdc9

#: black 000000 767676
color0  #191114
color8  #3c3235

#: red cc0403 f2201f
color1  #b7637d
color9  #e7ccd4

#: green 19cb00 23fd00
color2  #e1bdc9
color10 #fed9e5

#: yellow cecb00 fffd00
color3  #f1bb97
color11 #ffdcc6

#: blue 0d73cc 1a8fff (Modified to use Primary)
color4  #ffb0d0
color12 #ffd8e6

#: magenta cb1ed1 fd28ff (Modified to use bright Secondary instead of dark text variant)
color5  #e1bdc9
color13 #fed9e5

#: cyan 0dcdcd 14ffff (Modified to use Primary for Fastfetch Arch Logo)
color6  #ffb0d0
color14 #ffd8e6

#: white dddddd ffffff
color7  #d5c2c7
color15 #eedfe2

mark1_foreground #390722
mark1_background #ffd8e6
mark2_foreground #2a151e
mark2_background #fed9e5
mark3_foreground #301400
mark3_background #ffdcc6

active_tab_foreground #531d38
active_tab_background #ffb0d0
inactive_tab_foreground #ffd8e6
inactive_tab_background #6e334e

active_border_color #ffb0d0
inactive_border_color #531d38
# bell_border_color #ff5a00
