#################
### AUTOSTART ###
#################

# Wallpaper daemon
exec-once = swww-daemon

# Status Bar
exec-once = waybar

# Notifications
exec-once = swaync

# Idle daemon
exec-once = hypridle

# Clipboard history
exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store
exec-once = wl-clip-persist --clipboard regular

# Clear Clipboard history
exec-once = cliphist wipe

# Some important stuf
exec-once = /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1
exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP

# Discord :)
exec-once = discord --start-minimized
