#################
### AUTOSTART ###
#################

# Wallpaper daemon
exec-once = awww-daemon

# Status Bar
exec-once = waybar

# Notifications
exec-once = swaync

# Idle daemon
exec-once = hypridle

# Clipboard history
exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store
exec-once = wl-clip-persist --clipboard regular

# Clear Clipboard history
exec-once = cliphist wipe

# Some Theming Stuff
exec-once = pywalfox start
exec-once = sleep 2 && openrgb --profile ~/.config/OpenRGB/purple-white-pink.orp

# Discord :)
exec-once = discord --start-minimized
